services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - airflow_network
  
  webserver:
    image: apache/airflow:latest
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__CORE__EXECUTOR: 'LocalExecutor'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: 'postgresql+psycopg2://airflow:airflow@postgres:5432/airflow'
      AIRFLOW__WEBSERVER__SECRET_KEY: 'chave_secreta'
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dados:/opt/airflow/dados
    entrypoint: ["sh", "-c", "airflow db init && exec airflow webserver"]
    networks:
      - airflow_network

  scheduler:
    image: apache/airflow:latest
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__CORE__EXECUTOR: 'LocalExecutor'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: 'postgresql+psycopg2://airflow:airflow@postgres:5432/airflow'
      AIRFLOW__WEBSERVER__SECRET_KEY: 'chave_secreta'
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dados:/opt/airflow/dados
    command: ["scheduler"]
    networks:
      - airflow_network

networks:
  airflow_network:

volumes:
  postgres_data:
  airflow_data: